<h1> Пользователи </h1>
<a href="/admin/customer/add/" class="btn btn-default"> Добавить пользователя</a>
<?php
    $flash = $this->flashMessenger();
    $flash->setMessageOpenFormat('<div class="alert alert-dismissible alert-success">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
        &times;
    </button>
    <ul><li>')
        ->setMessageSeparatorString('</li><li>')
        ->setMessageCloseString('</li></ul></div>');

    echo $flash->render('error', array('alert', 'alert-dismissable', 'alert-danger'));
    echo $flash->render('info', array('alert', 'alert-dismissable', 'alert-info'));
    echo $flash->render('default', array('alert', 'alert-dismissable', 'alert-default'));
    echo $flash->render('success', array('alert', 'alert-dismissable', 'alert-success'));

$url_order = 'ASC';
if ($order_by == 'login') {
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
} elseif ($order_by == 'email') {
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
} elseif ($order_by == 'accountExpired') {
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
} ?>

<table class="table table-stripped table-hover">
    <tbody>
        <tr>
            <th>Avatar</th>
            <th>Category</th>
            <th><a href="<?php echo $this->url('admin/customer', array('order_by' => 'login', 'order' => $url_order)); ?>">Login </a></th>
            <th>Password</th>
            <th><a href="<?php echo $this->url('admin/customer', array('order_by' => 'email', 'order' => $url_order)); ?>">Email </a></th>
            <th>AvatarExtension</th>
            <th><a href="<?php echo $this->url('admin/customer', array('order_by' => 'accountExpired', 'order' => $url_order)); ?>">Account Expired </a></th>
            <th>Action</th>
        </tr>
        
<?php   foreach ($customers as $item) { 
        $category = $item->getCategory();
        if ($category) {
            $catName = $category->getCategoryName();
        } else {
            $catName = '';
        }
        $av = $_SERVER['DOCUMENT_ROOT'] . '/upload/' . $item->getId();
        if (!file_exists($av)) {
            $av = '/upload/default';
        } else {
            $av = '/upload/' . $item->getId();
        }
        ?>
        <tr>
            <td class="image-box"><img src="<?php echo $av; ?>" /></td> 
            <td><?php echo $this->escapeHtml($catName);?></td>
            <td><?php echo $this->escapeHtml($item->getLogin()); ?></td>
            <td><?php echo $this->escapeHtml($item->getPassword()); ?></td>
            <td><?php echo $this->escapeHtml($item->getEmail()); ?></td>
            <td><?php echo $this->escapeHtml($item->getAvatarExtension()); ?></td>
            <td><?php echo $this->escapeHtml($item->getAccountExpired()->format('Y-m-d H:i:s')); ?></td>
            <td>
                <a href="<?php echo $this->url('admin/customer', array(
                                            'action' => 'edit', 
                                            'id' => $item->getId())
                                            ); ?>" class='btn btn-info'>Редактировать</a>
                <a href="<?php echo $this->url('admin/customer', array(
                                            'action' => 'delete', 
                                            'id' => $item->getId())
                                            ); ?>" onclick="if (confirm('Удалить пользователя?')) { document.location = this.href; } return false; " class='btn btn-danger'>Удалить</a>
                <a href="<?php echo $this->url('admin/customer', array(
                                            'action' => 'upload', 
                                            'id' => $item->getId())
                                            ); ?>" class='btn btn-success'>Загрузить</a>
            </td>
        </tr>
<?php   } ?>
    </tbody>
</table>
<?php echo $this->paginationControl($customers, 'Sliding', 'pagination_control', array('route' => 'admin/customer')); ?>