<?php

$title = "New customer";
$this->headTitle($title);

//var_dump($this->form);
?>

<h1><?php echo $this->escapeHtml($title)?></h1>

<?php 
    
$form = $this->form;
$form->setAttribute("action", $this->url()); //"adminpage", array("action" => "add"
$form->prepare();

echo $this->form()->openTag($form);
//echo $this->formHidden($form->get("page")->get('id'));
echo $this->formCollection($form->get('id'));
//echo $this->formRow($form->get("group_id"));
//echo $this->formRow($form->get("login"));
//echo $this->formRow($form->get("email"));
//echo $this->formRow($form->get("password"));
//echo $this->formRow($form->get("account_expired"));
//echo $this->formSubmit($form->get("submit"));
 echo $this->form()->closeTag();
?>