<?php

$title = "Customers";
$this->headTitle($title);
?>


<h1><?php echo $this->escapeHtml($title)?></h1>
<a href="<?php echo $this->url("adminpage", array("action" => "add" ))?>">New customer</a>


<table class="table">
    <tr>
        <th>id_group</th>
        <th>UserName</th>
        <th>Password</th>
        <th>Email</th>
        <th>account_expired</th>
        <th>avatar_extension</th>
        <th>&nbsp;</th>
    </tr>
    
    <?php foreach($customer as $item){ ?>
    <tr>
        <td><?php echo $this->escapeHtml($item->group_id) ?></td>
        <td><?php echo $this->escapeHtml($item->login) ?></td>
        <td><?php echo $this->escapeHtml($item->password) ?></td>
        <td><?php echo $this->escapeHtml($item->email) ?></td>
        <td><?php echo $this->escapeHtml($item->account_expired) ?></td>
        <td><?php echo $this->escapeHtml($item->avatar_extension) ?></td>
        <td>
            <a href="<?php echo $this->url("adminpage", array("action" => "modify", "id" => $item->id ))?>">Редактировать</a>
            <a href="<?php echo $this->url("adminpage", array("action" => "delete", "id" => $item->id ))?>">Удалить</a>
        </td>
        
    </tr>
<?php }?>
</table>